name: 'astros_analytics'
version: '1.0.0'
config-version: 2

profile: 'clickhouse_profile'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  astros_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table